"""Prepare source and setFinalvF rendering archives without uploading or publishing.

Run from a companion repository checkout:
    python scripts/prepare_zenodo_release.py --ref v1.1.0 --out dist/zenodo-v1.1.0

The source ZIP is an exact git archive of the ref. Generated S10/S11 PDFs and
PNGs are copied separately and explicitly identified as composer previews.
The table deliverables come from the ref, not an uncommitted working copy.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import zipfile


def git(repo: Path, *args: str) -> bytes:
    result = subprocess.run(["git", "-C", str(repo), *args], capture_output=True)
    if result.returncode:
        raise RuntimeError(result.stderr.decode(errors="replace"))
    return result.stdout


def fingerprint(data: bytes) -> dict:
    return {"size_bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(),
            "md5": hashlib.md5(data).hexdigest()}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--ref", required=True)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()
    if not re.fullmatch(r"v\d+\.\d+\.\d+", args.ref):
        parser.error("--ref must be an existing version tag such as v1.1.0")
    repo = args.repo.resolve()
    commit = git(repo, "rev-parse", "--verify", f"refs/tags/{args.ref}^{{commit}}").decode().strip()
    # Renderings cannot be attributed to the tag if their inputs/scripts differ.
    changed = git(repo, "diff", "--name-only", commit, "--", "data", "interp", "topology", "figures").decode()
    changed_inputs = [path for path in changed.splitlines() if not path.endswith(".md")]
    if changed_inputs:
        raise SystemExit("Scientific inputs/scripts differ from the tag:\n" + "\n".join(changed_inputs))
    previews = {}
    for number in (10, 11):
        for suffix in ("pdf", "png"):
            rel = f"figures/setFinalvF/figS{number}/final/figure_S{number}.{suffix}"
            data = (repo / rel).read_bytes()
            magic = b"%PDF-" if suffix == "pdf" else b"\x89PNG\r\n\x1a\n"
            if not data.startswith(magic) or len(data) < 100_000:
                raise SystemExit(f"Missing or invalid rendering: {rel}")
            previews[rel] = data
    # A new output directory prevents accidental replacement of a reviewed bundle.
    args.out.mkdir(parents=True, exist_ok=False)
    out = args.out.resolve()
    version = args.ref.removeprefix("v")
    prefix = f"DeepCirc-interp-{version}/"
    source = out / f"DeepCirc-interp-{version}.zip"
    git(repo, "archive", "--format=zip", f"--prefix={prefix}", f"--output={source}", commit)
    files = []
    table_files = {}
    with zipfile.ZipFile(source) as archive:
        if archive.testzip():
            raise SystemExit("Source archive CRC check failed")
        for number in (1, 2, 3):
            for suffix in ("csv", "pdf", "png", "svg"):
                rel = f"figures/setFinalvF/tabS0{number}/final/table_S{number}.{suffix}"
                table_files[rel] = archive.read(prefix + rel)
        rel = "figures/setFinalvF/table_legends.md"
        table_files[rel] = archive.read(prefix + rel)
    readme = f"""# DeepCirc-interp {args.ref}: prepared Zenodo upload

Source commit: {commit}
Existing published version: https://doi.org/10.5281/zenodo.20576709 (v1.0.0)
All-versions DOI: https://doi.org/10.5281/zenodo.20576708

The source ZIP is the unmodified tagged source, including corrected data,
setFinalvF scripts, and the S1-S3 table deliverables. Its older README and
downloader still point to the v1.0.0 data deposit. For a v1.1 rebuild, use the
data already bundled in this ZIP; do not replace it with v1.0.0 downloads.
Install requirements and this package, then run `make figures-vf tables-vf`.
Arial is required by the table renderer. The source tag predates the CI-only
font installation fix at 7393b5f; that later CI run passed.

The separate setFinalvF ZIP contains existing composer previews (S10/S11,
PDF/PNG) plus the tagged S1-S3 tables (CSV/PDF/PNG/SVG) and table legends.
These figure PDFs are NOT final hand-composed Illustrator exports.
The rendering input/script files match the source tag; the PDFs/PNGs were
not regenerated by the packaging command. Checksums identify the exact files.
No .ai exports were found in setFinalvF when this package was prepared.
The source ZIP does not bundle the upstream private submodule or large
checkpoints/HDF5 datasets. Neither archive claims a complete full-data tier.

Resume the unpublished new-version draft of record 20576709, or create it
through New version on that record. Confirm conceptrecid 20576708 before
upload. Upload the two ZIPs, this README, and manifest.json. metadata.json contains
proposed descriptive updates, not a complete API request or an additional dataset.
Merge its metadata_patch into the draft's current metadata, preserving existing
creators, ORCIDs, affiliations, license, and other bibliographic fields. Review inherited v1.0 files
in the draft so the release does not present an old source ZIP as current.
Verify uploaded sizes and MD5 values against manifest.json before publishing.
This command performs no network calls, uploads, or publication.
"""
    rendering = out / f"DeepCirc-interp-{version}-setFinalvF-previews-and-tables.zip"
    with zipfile.ZipFile(rendering, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for rel, data in sorted({**previews, **table_files}.items()):
            info = zipfile.ZipInfo("setFinalvF/" + rel.split("setFinalvF/", 1)[1], (2026, 10, 7, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, data)
            files.append({"path": rel, "origin": "working-tree composer preview" if rel in previews else "git tag", **fingerprint(data)})
        archive.writestr("README.md", readme)
    with zipfile.ZipFile(rendering) as archive:
        if archive.testzip():
            raise SystemExit("Rendering archive CRC check failed")
    metadata = {
        "title": "DeepCirc-interp: interpretability companion code, setFinalvF figures and supplementary tables",
        "version": args.ref,
        "description": "<p>Interpretability companion code for the DeepCirc paper. This version adds setFinalvF: scripts and intermediate data for supplementary figures S10 and S11, plus supplementary tables S1-S3, alongside the preserved v1.0 setFinal analysis. It includes corrected family-unique coalition sampling and regenerated Shapley and Shapley-Taylor results.</p><p>The source archive is the tagged companion repository. A separate rendering archive includes generated S10/S11 composer previews and the S1-S3 table deliverables with legends. Composer previews are not final hand-composed Illustrator artwork. Full training checkpoints, exemplar HDF5 datasets, and the upstream private submodule are not bundled.</p>",
        "notes": f"Source tag {args.ref}, commit {commit}. See README-ZENODO.md and manifest.json for contents, provenance and checksums. Continues the manually uploaded record series with concept DOI 10.5281/zenodo.20576708.",
    }
    (out / "README-ZENODO.md").write_text(readme)
    (out / "metadata.json").write_text(json.dumps({"metadata_patch": metadata}, indent=2) + "\n")
    artifacts = [{"filename": p.name, **fingerprint(p.read_bytes())}
                 for p in (source, rendering, out / "README-ZENODO.md", out / "metadata.json")]
    manifest = {"source_tag": args.ref, "source_commit": commit,
                "conceptrecid": "20576708", "previous_record_id": "20576709",
                "status": "prepared locally; not uploaded or published",
                "artifacts": artifacts, "rendering_contents": files}
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps({"directory": str(out), "artifacts": artifacts}, indent=2))


if __name__ == "__main__":
    main()
